CREATE TABLE IF NOT EXISTS reservations (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    holder_id VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS seats (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    row_label VARCHAR(255) NOT NULL,
    seat_number VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL,
    held_by VARCHAR(255),
    held_until TIMESTAMP NULL DEFAULT NULL,
    reservation_id BIGINT,
    CONSTRAINT fk_seats_reservation FOREIGN KEY (reservation_id) REFERENCES reservations(id)
);

CREATE INDEX IF NOT EXISTS idx_status ON seats(status);
CREATE INDEX IF NOT EXISTS idx_held_until ON seats(held_until);

SET FOREIGN_KEY_CHECKS = 0;
TRUNCATE TABLE seats;
TRUNCATE TABLE reservations;
SET FOREIGN_KEY_CHECKS = 1;

INSERT INTO seats (row_label, seat_number, status)
SELECT r.row_label, CAST(n.seat_number AS CHAR), 'AVAILABLE'
FROM (
    SELECT 'A' AS row_label UNION ALL
    SELECT 'B' UNION ALL
    SELECT 'C' UNION ALL
    SELECT 'D' UNION ALL
    SELECT 'E'
) r
CROSS JOIN (
    SELECT 1 AS seat_number UNION ALL SELECT 2 UNION ALL SELECT 3 UNION ALL SELECT 4 UNION ALL SELECT 5
    UNION ALL SELECT 6 UNION ALL SELECT 7 UNION ALL SELECT 8 UNION ALL SELECT 9 UNION ALL SELECT 10
) n;
