CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    starts_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS reservations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES events(id),
    holder_id VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS seats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES events(id),
    row_label VARCHAR(255) NOT NULL,
    seat_number VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL,
    held_by VARCHAR(255),
    held_until TIMESTAMP,
    reservation_id BIGINT REFERENCES reservations(id)
);

CREATE INDEX IF NOT EXISTS idx_event_status ON seats(event_id, status);
CREATE INDEX IF NOT EXISTS idx_held_until ON seats(held_until);

BEGIN;

TRUNCATE TABLE seats, reservations, events RESTART IDENTITY CASCADE;

WITH new_event AS (
    INSERT INTO events (name, starts_at)
    VALUES ('Demo Concert', now() + interval '1 day')
    RETURNING id
)
INSERT INTO seats (event_id, row_label, seat_number, status)
SELECT e.id, r.row_label, s.seat_number::text, 'AVAILABLE'
FROM new_event e
CROSS JOIN unnest(ARRAY['A','B','C','D','E']) AS r(row_label)
CROSS JOIN generate_series(1, 10) AS s(seat_number);

COMMIT;
