events {}

http {
    upstream backend_pool {
        server backend-1:8080;
        server backend-2:8080;
    }

    server {
        listen 8080;

        location /api/ {
            proxy_pass http://backend_pool;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header Connection '';
            proxy_buffering off;
            proxy_cache off;
            proxy_read_timeout 3600s;
        }
    }
}
